github.com:
    users:
        rockstarlife:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: rockstarlife
